name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore Dependencies
      run: dotnet restore Shopzy.sln

    - name: Build Project
      run: dotnet build Shopzy.sln --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test Shopzy.sln --no-build --verbosity normal
